# Generated by Django 5.0.7 on 2024-07-22 19:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Team',
            new_name='Teams',
        ),
    ]
